web/config/routes.rb
Rails.application.routes.draw do
  root :to => "homepage#home"

  devise_for :users,
             :only => [:sessions],
             :controllers => { :sessions => "users/sessions" }

  as :user do
    get "sign_up" => "devise/registrations#new", :as => :new_user_registration
    post "user" => "devise/registrations#create", :as => :user_registration
  end

  authenticate :user do
    resources :book, :only => %i[create new edit show update destroy], :param => :book_slug do
      resources :entry, :only => %i[create show update destroy]
      resources :extractor, :only => %i[create new show update destroy]
      resources :shorthand, :only => %i[create new show update destroy]
      get "/at/:requested_time", :to => "book#show", :as => :at
    end

    resource :search, :only => %i[show]
    resource :user, :only => %i[show update]

    resources :report, :only => %i[new edit show update create destroy] do
      resources :report_variable, :only => %i[new edit update create destroy]
      resources :report_output, :only => %i[new edit update create destroy]
    end

    post "/query/execute", :to => "query#execute"
  end

  namespace :api do
    namespace :v1 do
      resources :token, :only => %i[create]
      resources :books, :only => %i[index] do
        resources :entries, :only => %i[create]
      end
    end
  end
end

web/app/views/layouts/_content-view.html.erb
<%= render "layouts/header" %>

<div class="content-view db w-100 pt4 pt5-ns pb5 pa2 ph5-l">
  <div class="measure-wide">
    <%= yield %>
  </div>
</div>

web/app/views/layouts/_full-content-view.html.erb
<%= render "layouts/header" %>

<div class="content-view pa2 ph2 pv5-l ph5-l">
  <%= yield %>
</div>

web/app/views/layouts/_header.html.erb
<% if alert %>
  <p class="tc f5 bg-washed-red bb b--dark-red pa2 ma0"><%= alert %></p>
<% end %>
<header>
  <nav class="flex justify-between pa2 ph2 ph5-l bb b--black-10 ">
    <div class="flex items-center">
      <a href="/" class="link black i baskerville f3 nowrap">
        Captain&rsquo;s Log
      </a>
      <div class="dn db-l lh-copy f6 ml3"><%= notice %></div>
    </div>
    <div class="flex-grow flex items-center">
      <span class="search dn-ns">
        <%= link_to image_tag("search.svg"), :search %>
      </span>
      <form action="<%= search_path %>" class="search nowrap dn dib-ns">
        <label>
          <input type="text" name="query" />
          <%= image_tag("search.svg") %>
        </label>
      </form>
      <%= link_to t(:create_book), new_book_path, :class => "blue link f6 mh3 dn dib-l" %>
      <%= link_to t(:create_report), new_report_path, :class => "blue link f6 mh3 dn dib-l" %>
      <%= link_to t(:settings), user_path, :class => "blue link f6 mh3 dn dib-l" %>
      <%= link_to t(:sign_out), destroy_user_session_path,
        :method => :delete,
        :class => "blue link f6 bg-animate hover-bg-black-10 pv2 ph3 br-pill" %>
    </div>
  </nav>
</header>

<%= render "layouts/navigation", :books => current_user.books, :reports => current_user.reports %>

web/app/views/layouts/_navigation.html.erb
<div class="pa2 ph2 ph5-l bb b--black-10 absolute-l w-100">
  <% reports.each do |report| %>
    <%= link_to report.label, report_path(report),
      :class => "link black f6 mr3" %>
  <% end %>
  <% books.each do |book| %>
    <%= link_to book.name, book_path(book.slug),
      :class => "link black f6 mr3" %>
  <% end %>
</div>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title><%= t(:captains_log) %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>