web/config/routes.rb
Rails.application.routes.draw do
  root :to => "homepage#home"

  devise_for :users,
             :only => [:sessions],
             :controllers => { :sessions => "users/sessions" }

  as :user do
    get "sign_up" => "devise/registrations#new", :as => :new_user_registration
    post "user" => "devise/registrations#create", :as => :user_registration
  end

  authenticate :user do
    resources :book, :only => %i[create new edit show update destroy], :param => :book_slug do
      resources :entry, :only => %i[create show update destroy]
      resources :extractor, :only => %i[create new show update destroy]
      resources :shorthand, :only => %i[create new show update destroy]
      get "/at/:requested_time", :to => "book#show", :as => :at
    end

    resource :search, :only => %i[show]
    resource :user, :only => %i[show update]

    resources :report, :only => %i[new edit show update create destroy] do
      resources :report_variable, :only => %i[new edit update create destroy]
      resources :report_output, :only => %i[new edit update create destroy]
    end

    post "/query/execute", :to => "query#execute"
  end

  namespace :api do
    namespace :v1 do
      resources :token, :only => %i[create]
      resources :books, :only => %i[index] do
        resources :entries, :only => %i[create]
      end
    end
  end
end

web/app/models/report_variable.rb
class ReportVariable < ApplicationRecord
  belongs_to :report

  validates :label, :report, :presence => true
end

web/app/controllers/report_variable_controller.rb
class ReportVariableController < UserSessionController
  # === URL
  #   GET /report/:report_id/report_variable/new
  #
  # === Sample request
  #   /report/12/report_variable/new
  #
  def new
    locals :report_variable => ReportVariable.new(:report => current_report)
  end

  # === URL
  #   GET /report/:report_id/report_variable/:id/edit
  #
  # === Request fields
  #   [Integer] report_id - the id of the owning report
  #   [Integer] id - the id of the report variable to edit
  #
  # === Sample request
  #   /report/4/report_variable/3/edit
  #
  def edit
    locals :report_variable => current_report_variable
  end

  # === URL
  #   POST /report/:report_id/report_variable
  #
  # === Request fields
  #   [Integer] report_id - the report to add the variable to
  #   [String] report_variable[label] - the report variable's label
  #   [String] report_variable[default_value] - the report variable's default value
  #   [String] report_variable[query] - the report variable's query
  #
  # === Sample request
  #   /report/12/report_variable
  #
  def create
    report_variable = create_report_variable
    ok = report_variable.persisted?
    notify(ok, :successful_report_variable_create, :failure_in_report_variable_create)
    ok ? redirect_to(edit_report_path(current_report)) : locals(:new, :report_variable => report_variable)
  end

  # === URL
  #   PATCH /report/:report_id/report_variable/:id
  #
  # === Request fields
  #   [Integer] report_id - the report that the variable belongs to
  #   [Integer] id - the report variable to update
  #   [String] report_variable[label] - the report variable's label
  #   [String] report_variable[default_value] - the report variable's default value
  #   [String] report_variable[query] - the report variable's query
  #
  # === Sample request
  #   /report/12/report_variable/2
  #
  def update
    ok = update_report_variable
    notify(ok, :successful_report_variable_update, :failure_in_report_variable_update)
    ok ? redirect_to(edit_report_path(current_report)) : locals(:edit, :report_variable => current_report_variable)
  end

  # === URL
  #   DELETE /report/:report_id/report_variable/:id
  #
  # === Request fields
  #   [Integer] report_id - the report that the variable belongs to
  #   [Integer] id - the report variable to update
  #
  # === Sample request
  #   /report/12/report_variable/2
  #
  def destroy
    current_report_variable.destroy
    flash.notice = t(:successful_report_variable_delete)
    redirect_to(edit_report_path(current_report))
  end

private

  param_reader :id
  param_reader :report_id

  # @return [ReportVariable]
  def create_report_variable
    extra = { :report => current_report }
    attrs = permitted_report_variable_params.to_hash.merge(extra)
    ReportVariable.create(attrs)
  end

  # @return [Report]
  def current_report
    current_user.reports.find(report_id)
  end

  # @return [ReportVariable]
  def current_report_variable
    current_report.variables.find(id)
  end

  # Update the report variable and return true if there were not errors doing so.
  #
  # @return [Boolean]
  def update_report_variable
    current_report_variable.update(permitted_report_variable_params)
    current_report_variable.errors.empty?
  end

  # @return [ActionController::Parameters]
  def permitted_report_variable_params
    params.require(:report_variable)
          .permit(:label, :default_value, :query)
  end
end

web/app/views/report_variable/_edit_form.html.erb
<%= form_for(report_variable, :url => report_variable.id.present? ? report_report_variable_path(report_variable.report, report_variable) : report_report_variable_index_path) do |f| %>
  <%= render "form/field", :f => f, :field => :label %>
  <%= render "form/field", :f => f, :field => :default_value %>
  <%= render "form/field", :f => f, :field => :query do %>
    <textarea
      id="report_variable_query"
      name="report_variable[query]"
      rows="10"
      class="code ba b--black-10 pa2 w-100 mb2"
    ><%= report_variable.query %></textarea>
  <% end %>

  <%= render "form/timestamps", :f => f %>
  <%= render "form/actions", :f => f, :paths => {
    :back => user_path,
    :delete => report_variable.persisted? && report_report_variable_path(report_variable.report, report_variable),
  } %>
<% end %>

web/app/views/report_variable/_list.html.erb
<div class="overflow-auto">
  <table class="f6 w-100 collapse">
    <tr>
      <th class="nowrap fw6 bb b--black-10 tl pb3 pr3 w4"><%= t(:label) %></td>
      <th class="nowrap fw6 bb b--black-10 tl pb3 pr3 w4"><%= t(:default_value) %></td>
      <th class="nowrap fw6 bb b--black-10 tl pb3 pr3 w4"><%= t(:query) %></td>
    </tr>
    <% variables.each do |variable| %>
      <tr>
        <td class="nowrap pv3 pr3 bb b--black-10"><%= link_to variable.label, edit_report_report_variable_path(report, variable), :class => "link blue" %></td>
        <td class="nowrap pv3 pr3 bb b--black-10"><%= variable.default_value %></td>
        <td class="nowrap pv3 pr3 bb b--black-10 code"><%= variable.query.truncate(80) %></td>
      </tr>
    <% end %>
  </table>
</div>

web/app/views/report_variable/edit.html.erb
<%= render "layouts/content-view" do %>
  <%= render "form/title", :key => :edit_report_variable %>
  <%= render "report_variable/edit_form", :report_variable => report_variable %>
<% end %>

web/app/views/report_variable/new.html.erb
<%= render "layouts/content-view" do %>
  <%= render "form/title", :key => :add_report_variable %>
  <%= render "report_variable/edit_form", :report_variable => report_variable %>
<% end %>