web/config/routes.rb
Rails.application.routes.draw do
  root :to => "homepage#home"

  devise_for :users,
             :only => [:sessions],
             :controllers => { :sessions => "users/sessions" }

  as :user do
    get "sign_up" => "devise/registrations#new", :as => :new_user_registration
    post "user" => "devise/registrations#create", :as => :user_registration
  end

  authenticate :user do
    resources :book, :only => %i[create new edit show update destroy], :param => :book_slug do
      resources :entry, :only => %i[create show update destroy]
      resources :extractor, :only => %i[create new show update destroy]
      resources :shorthand, :only => %i[create new show update destroy]
      get "/at/:requested_time", :to => "book#show", :as => :at
    end

    resource :search, :only => %i[show]
    resource :user, :only => %i[show update]

    resources :report, :only => %i[new edit show update create destroy] do
      resources :report_variable, :only => %i[new edit update create destroy]
      resources :report_output, :only => %i[new edit update create destroy]
    end

    post "/query/execute", :to => "query#execute"
  end

  namespace :api do
    namespace :v1 do
      resources :token, :only => %i[create]
      resources :books, :only => %i[index] do
        resources :entries, :only => %i[create]
      end
    end
  end
end

web/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  has_many :report_outputs, :dependent => :destroy
  has_many :report_variables, :dependent => :destroy

  alias_attribute :outputs, :report_outputs
  alias_attribute :variables, :report_variables

  validates :label, :user, :presence => true

  default_scope { order(:created_at => :asc) }

  def dump
    {
      :id => id,
      :label => label,
      :variables => dump_variables,
      :outputs => dump_outputs
    }
  end

private

  def dump_variables
    variables.map do |variable|
      {
        :id => variable.id,
        :label => variable.label,
        :query => variable.query,
        :defaultValue => variable.default_value
      }
    end
  end

  def dump_outputs
    outputs.map do |output|
      {
        :id => output.id,
        :label => output.label,
        :width => output.width,
        :height => output.height,
        :kind => output.kind,
        :query => output.query
      }
    end
  end
end

web/app/controllers/report_controller.rb
class ReportController < UserSessionController
  # === URL
  #   GET /report/new
  #
  # === Sample request
  #   /report/new
  #
  def new
    locals :report => Report.new
  end

  # === URL
  #   GET /report/:id
  #
  # === Request fields
  #   [Integer] id - the id of the report to show
  #
  # === Sample request
  #   /report/4
  #
  def show
    locals :report => current_report
  end

  # === URL
  #   GET /report/:id/edit
  #
  # === Request fields
  #   [Integer] id - the id of the report to show
  #
  # === Sample request
  #   /report/4/edit
  #
  def edit
    locals :report => current_report
  end

  # === URL
  #   POST /report
  #
  # === Request fields
  #   [String] report[label] - the report label
  #
  # === Sample request
  #   /report
  #
  def create
    report = create_report
    ok = report.persisted?
    notify(ok, :successful_report_create, :failure_in_report_create)
    ok ? redirect_to(edit_report_path(report)) : locals(:new, :report => report)
  end

  # === URL
  #   PATCH /report/:id
  #
  # === Request fields
  #   [String] report[label] - the report label
  #
  # === Sample request
  #   /report/12
  #
  def update
    ok = update_report
    notify(ok, :successful_report_update, :failure_in_report_update)
    ok ? redirect_to(edit_report_path(current_report)) : locals(:edit, :report => current_report)
  end

  # === URL
  #   DELETE /report/:id
  #
  # === Request fields
  #   [Integer] id - the id for the report to delete
  #
  # === Sample request
  #   /book/12
  #
  def destroy
    current_report.destroy
    flash.notice = t(:successful_report_delete)
    redirect_to(user_path)
  end

private

  param_reader :id

  # @return [Report]
  def current_report
    current_user.reports.find(id)
  end

  # @return [Report]
  def create_report
    extra = { :user => current_user }
    attrs = permitted_report_params.to_hash.merge(extra)
    Report.create(attrs)
  end

  # Update the report and return true if there were not errors doing so.
  #
  # @return [Boolean]
  def update_report
    current_report.update(permitted_report_params)
    current_report.errors.empty?
  end

  # @return [ActionController::Parameters]
  def permitted_report_params
    params.require(:report)
          .permit(:label)
  end
end

web/app/views/report/_edit_form.html.erb
<%= form_for(report, :url => report.id.present? ? report_path(report) : report_index_path) do |f| %>
  <%= render "form/field", :f => f, :field => :label %>
  <%= render "form/timestamps", :f => f %>

  <%= render "form/actions", :f => f,
    :paths => { :back => user_path, :delete => report } do %>
    <%= block_given? && yield %>
  <% end %>
<% end %>

web/app/views/report/_list.html.erb
<div class="overflow-auto">
  <table class="f6 w-100 collapse">
    <tr>
      <th class="nowrap fw6 bb b--black-10 tl pb3 pr3 w4"><%= t(:name) %></td>
      <th class="nowrap fw6 bb b--black-10 tl pb3 pr3 w4"><%= t(:variables) %></td>
      <th class="nowrap fw6 bb b--black-10 tl pb3 pr3 w4"><%= t(:outputs) %></td>
    </tr>
    <% reports.each do |report| %>
      <tr>
        <td class="nowrap pv3 pr3 bb b--black-10"><%= link_to report.label, edit_report_path(report), :class => "link blue" %></td>
        <td class="nowrap pv3 pr3 bb b--black-10"><%= report.variables.count %></td>
        <td class="nowrap pv3 pr3 bb b--black-10"><%= report.outputs.count %></td>
      </tr>
    <% end %>
  </table>
</div>

web/app/views/report/edit.html.erb
<%= render "layouts/full-content-view" do %>
  <div class="measure-wide">
    <%= render "form/title", :key => :edit_report %>
    <%= render "report/edit_form", :report => report do %>
      <%= link_to t(:create_report_variable), new_report_report_variable_path(report.id), :class => "f6 link ml4 blue" %>
      <%= link_to t(:create_report_output), new_report_report_output_path(report.id), :class => "f6 link ml2 blue" %>
    <% end %>
  </div>

  <%= render "form/subtitle", :key => :variables %>
  <%= render "report_variable/list", :report => report, :variables => report.variables %>

  <%= render "form/subtitle", :key => :outputs %>
  <%= render "report_output/list", :report => report, :outputs => report.outputs %>
<% end %>

web/app/views/report/new.html.erb
<%= render "layouts/content-view" do %>
  <%= render "form/title", :key => :create_report %>
  <%= render "report/edit_form", :report => report %>
<% end %>

web/app/views/report/show.html.erb
<%= render "layouts/content-view" %>
<script>
const REPORT = <%= report.dump.to_json.html_safe %>
</script>
<%= javascript_include_tag "/assets/report_builder.bundle.js" %>